### ISSUE TITLE
Scipy 1.8.0 breaks bandpass filter

### ISSUE THREAD

**Issue by sjoerd-bouma** [nu-radio/NuRadioMC#404]
As of version 1.8.0, scipy [raises an error if the passband includes a frequency <=0](https://github.com/scipy/scipy/commit/5fc8ab679f9638e06c59fb627abe9a3df14b59e4). As we often specify lowpass filters by giving 0 as the lower frequency, this means that `NuRadioReco.utilities.bandpass_filter` breaks.

Error message:
```
Traceback (most recent call last):
  File "NuRadioMC/test/SingleEvents/T02RunSimulation.py", line 77, in <module>
    sim = mySimulation(inputfilename=args.inputfilename,
  File "/home/sb/Python/software/nu-radio/NuRadioMC/NuRadioMC/simulation/simulation.py", line 311, in __init__
    filt *= instance.get_filter(ff, self._station_id, channel_id, self._det, **kwargs)
  File "/home/sb/Python/software/nu-radio/NuRadioMC/NuRadioReco/modules/channelBandPassFilter.py", line 145, in get_filter
    return bandpass_filter.get_filter_response(frequencies, tmp_passband, tmp_filter_type, tmp_order, tmp_rp)
  File "/home/sb/Python/software/nu-radio/NuRadioMC/NuRadioReco/utilities/bandpass_filter.py", line 38, in get_filter_response
    b, a = scipy.signal.butter(order, passband, 'bandpass', analog=True)
  File "/home/sb/Python/.venv/test-env/lib/python3.8/site-packages/scipy/signal/_filter_design.py", line 3045, in butter
    return iirfilter(N, Wn, btype=btype, analog=analog,
  File "/home/sb/Python/.venv/test-env/lib/python3.8/site-packages/scipy/signal/_filter_design.py", line 2463, in iirfilter
    raise ValueError("filter critical frequencies must be greater than 0")
```

This doesn't show up in the unit tests, because scipy 1.8.0 requires Python >= 3.8, and we run our tests on 3.7.

**Comment by cg-laser** [comment]
shall we move the tests to p3.8?

**Comment by sjoerd-bouma** [comment]
I'm not sure what the best Python version is for the tests (we could consider running the tests on multiple versions of Python on pushes to `develop` to catch stuff like this?). Maybe it makes sense to update to Python 3.8 (or newer?) by default, though.
