### ISSUE TITLE
`numba` implementation for ARZ breaks if wrong versions of numba/numpy/llvmlite are installed

### ISSUE THREAD

**Issue by sjoerd-bouma** [nu-radio/NuRadioMC#407]
Depending on the installed versions of `numba`, `numpy` and `llvmlite`, the quicker (numba) implementation of the ARZ signal generation may fail with the following error:
```
Traceback (most recent call last):
  File "NuRadioMC/test/SingleEvents/T02RunSimulation.py", line 85, in <module>
    sim.run()
  File "/home/sb/Python/software/nu-radio/NuRadioMC/NuRadioMC/simulation/simulation.py", line 735, in run
    self._cfg['signal']['model'], seed=self._cfg['seed'], full_output=True, **kwargs)
  File "/home/sb/Python/software/nu-radio/NuRadioMC/NuRadioMC/SignalGen/askaryan.py", line 161, in get_frequency_spectrum
    tmp = get_time_trace(energy, theta, N, dt, shower_type, n_index, R, model, full_output=full_output, **kwargs)
  File "/home/sb/Python/software/nu-radio/NuRadioMC/NuRadioMC/SignalGen/askaryan.py", line 107, in get_time_trace
    trace = gARZ.get_time_trace(energy, theta, N, dt, shower_type, n_index, R, same_shower=same_shower, **kwargs)[1]
  File "/home/sb/Python/software/nu-radio/NuRadioMC/NuRadioMC/SignalGen/ARZ/ARZ.py", line 604, in get_time_trace
    shift_for_xmax=shift_for_xmax, **model_parameters, em_factor=em_factor
TypeError: expected dtype object, got 'numpy.dtype[float64]'
```
One configuration for which this error occurs is `Python==3.7.13, numpy==1.21.6, numba==0.50.1, llvmlite==0.33.0`. Confirmed to work (on Ubuntu 20.04) is `Python==3.7.13, numpy==1.21.6, numba==0.55.1, llvmlite==0.38.0`

**Solution**
In most cases, I expect this can be solved by upgrading `numba` and/or `llvmlite`; in exceptional cases a downgrade of a very new `numpy` version may become necessary.

Unfortunately, due to the nature of `numba` and the way we specify our requirements (i.e. not really), this may show up more frequently.

**Comment by fschlueter** [comment]
@sjoerd-bouma is that solved?
