### ISSUE TITLE
uproot 4.1.1 doesn't work with awkward >= 2

### ISSUE THREAD

**Issue by sjoerd-bouma** [nu-radio/NuRadioMC#522]
@boboeyen flagged that reading RNO-G data files raises an error with `awkward>=2`. This seems to be an uproot issue.

MWE (thanks Bob):
```
import NuRadioReco.detector.detector
from NuRadioReco.utilities import units
import NuRadioReco.modules.io.rno_g.readRNOGData
det = NuRadioReco.detector.detector.Detector(json_filename='RNO_G/RNO_season_2021.json', antenna_by_depth=False)
data_reader = NuRadioReco.modules.io.rno_g.readRNOGData.readRNOGData()
data_reader.begin('./data/inbox/station21/run2100/combined.root')
for event in data_reader.run():
   print(event.get_id())
```

Error message:
```
Traceback (most recent call last):
  File "/home/sb/Python/scratch/debugging/awkward_error.py", line 7, in <module>
    for event in data_reader.run():
  File "/home/sb/Python/software/nu-radio/NuRadioMC/NuRadioReco/modules/io/rno_g/readRNOGData.py", line 157, in run
    for event_headers, events in zip(self.uproot_iterator_header, self.uproot_iterator_data):
  File "/home/sb/Python/.venv/test/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 205, in iterate
    for item in hasbranches.iterate(
  File "/home/sb/Python/.venv/test/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 1354, in iterate
    _ranges_or_baskets_to_arrays(
  File "/home/sb/Python/.venv/test/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 3494, in _ranges_or_baskets_to_arrays
    uproot.source.futures.delayed_raise(*obj)
  File "/home/sb/Python/.venv/test/lib/python3.10/site-packages/uproot/source/futures.py", line 46, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/home/sb/Python/.venv/test/lib/python3.10/site-packages/uproot/behaviors/TBranch.py", line 3464, in basket_to_array
    arrays[branch.cache_key] = interpretation.final_array(
  File "/home/sb/Python/.venv/test/lib/python3.10/site-packages/uproot/interpretation/numerical.py", line 115, in final_array
    output = library.finalize(output, branch, self, entry_start, entry_stop)
  File "/home/sb/Python/.venv/test/lib/python3.10/site-packages/uproot/interpretation/library.py", line 487, in finalize
    if isinstance(array, awkward.layout.Content):
AttributeError: module 'awkward' has no attribute 'layout'. Did you mean: 'to_layout'?
```

The easiest fix for the moment is probably to fix `awkward<2`. Long term, we may want to upgrade uproot (assuming #331 has been fixed - right now the latest version of uproot also throws errors when trying to open RNO-G files).

**Comment by sjoerd-bouma** [comment]
Closed by #694 as we no longer need to pin uproot to 4.1.1
